This builds patched ~wined3d.dll~ for the original Diablo on Wine. Currently
only supports Linux (see [[https://github.com/NixOS/nixpkgs/issues/8849][NixOS/nixpkgs#8849]]). Patch by [[https://github.com/galaxyhaxz][@galaxyhaxz]], sourced
from: https://forum.winehq.org/viewtopic.php?t=22340

** Install

Grab prebuilt DLL from [[https://github.com/yegortimoshenko/wined3d.dll/releases][GitHub Releases]], preferably version that matches your
Wine version. Copy it to ~$WINEPREFIX/drive_c/Diablo/wined3d.dll~ and then set
Diablo.exe DDraw renderer to GDI:

: wine REG ADD HKEY_CURRENT_USER\\Software\\Wine\\AppDefaults\\Diablo.exe\\Direct3D /V DirectDrawRenderer /T REG_SZ /D gdi

When you run the game, main menu should now be visible, but not without visual
glitches: animated images update only on mouse hover.

Also please mind that, as of 2.11-staging, Diablo does not run on Wine staging,
probably due to [[https://github.com/wine-compholio/wine-staging/tree/v2.21/patches][some DDraw patch]].

** Build from source

You will need [[https://nixos.org/nix/][Nix]]. Once installed, run ~nix-build -A <target>~ inside this
repo's directory, where target can be ~stable~, ~development~ or ~staging~.
After the build is completed, ~result~ will point to patched DLL.
